=== The Cypher Query Widget Example

If you haven't installed Neo4j on your machine, the Cypher Query widget is there for you to interactively explore, learn and get comfortable with Cypher in a safe environment.
You can't break anything, and if so, just reset the temporary database to its original state.

==== Example Gadget Number One!

++++
<iframe src="../test.html?cypherSetup=full&cypherTask=matchByNodeLabel" width="750" height="1000" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
++++

The different widgets use different datasets, depending on the task, but save your changes across sessions.
For most lab exercises we added helpful checks and messages to guide you along.

The query results are shown in a tabular view, and if you return nodes or relationships, those will be highlighted in the graph visualization of the dataset.
Complex elements are folded in the table and can be expanded with a click.

Your history is available across sessions. And we provide some pre-canned queries to get you started quickly.

Please try to work with the tasks on your own and not just copy & paste queries.
Thinking about them and writing & executing them incrementally helps you much more in understanding the concepts.

==== Example Gadget Number Two!

++++
<iframe src="../test.html?cypherSetup=full&cypherTask=matchByNodeLabel" width="750" height="1000" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
++++