// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Cypher;
    return Cypher = (function() {
      function Cypher() {}

      Cypher.prototype.initialize = function() {};

      Cypher.prototype.interpret = function(data) {
        var results;
        results = {
          columns: data.columns,
          rows: []
        };
        results.rows = _.map(data.json, function(row) {
          return _.map(row, function(datum) {
            if (_.has(datum, "_type")) {
              return {
                type: "relationship",
                properties: datum
              };
            } else if (_.has(datum, "_id")) {
              return {
                type: "node",
                properties: datum
              };
            } else if (_.isArray(datum)) {
              return {
                type: "collection",
                collection: datum
              };
            } else {
              return datum;
            }
          });
        });
        return results;
      };

      Cypher.prototype.submitQuery = function(query) {
        return $.ajax({
          type: "POST",
          url: "http://neo4j-training-backend.herokuapp.com/backend/cypher",
          data: query,
          dataType: 'text',
          xhrFields: {
            withCredentials: true
          },
          error: function(xhr, err, msg) {
            var errmsg;
            errmsg = JSON.parse(xhr.responseText).message;
            return $('body').append($("<div class='error'>").text(errmsg));
          }
        });
      };

      return Cypher;

    })();
  });

}).call(this);
